services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todolist
      MYSQL_USER: todolist
      MYSQL_PASSWORD: todolist
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
volumes:
  db:
